import assert from 'node:assert/strict';
import { createHarness } from './counter-harness.mjs';
const h = await createHarness();
let success = false;
try {
  await h.start();
  const page = await h.page();
  let release;
  const gate = new Promise(resolve => { release = resolve; });
  await page.route('**/api/counter', async route => { await gate; await route.continue().catch(() => {}); });
  await page.goto(h.url, { waitUntil: 'domcontentloaded' });
  await page.getByText('正在读取计数…', { exact: true }).waitFor();
  assert.equal(await page.getByTestId('counter-value').innerText(), '—');
  assert.equal(await page.getByRole('button', { name: '加一', exact: true }).isDisabled(), true);
  await h.screenshot(page, 'loading');
  release();
  await h.visible(page, 0);
  await page.unroute('**/api/counter');
  h.pass('Initial loading never displays a fake zero; real query returns zero');

  let releaseWrite;
  const writeGate = new Promise(resolve => { releaseWrite = resolve; });
  let requests = 0;
  await page.route('**/api/counter/increment', async route => { requests++; await writeGate; await route.continue(); });
  await page.getByRole('button', { name: '加一', exact: true }).click();
  await page.getByText('正在保存，请稍候…', { exact: true }).waitFor();
  for (const name of ['加一', '减一', '重新读取']) assert.equal(await page.getByRole('button', { name, exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: '加一', exact: true }).evaluate(button => { button.click(); button.click(); });
  assert.equal(await page.getByTestId('counter-value').innerText(), '0');
  await h.screenshot(page, 'saving');
  releaseWrite();
  await h.visible(page, 1);
  assert.equal(requests, 1);
  await page.unroute('**/api/counter/increment');
  await h.stored(1, 'single-write');
  h.pass('Pending request disables all actions, sends one POST, displays only confirmed value');
  await h.click(page, 'decrement', 0);
  await h.click(page, 'decrement', -1);
  await page.reload(); await h.visible(page, -1);
  const second = await h.page(); await second.goto(h.url); await h.visible(second, -1);
  await h.stored(-1, 'negative');
  await h.screenshot(page, 'negative');
  await h.screenshot(second, 'incognito');
  h.pass('Negative values, refresh and independent browser context agree with MySQL');
  await h.dc(['stop', 'db']);
  await page.getByRole('button', { name: '加一', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: '操作未确认' }).waitFor();
  assert.equal(await page.getByTestId('counter-value').innerText(), '-1');
  assert.equal(await page.getByRole('button', { name: '加一', exact: true }).isDisabled(), true);
  await h.screenshot(page, 'write-error');
  await second.reload();
  await second.getByRole('alert').filter({ hasText: '读取失败' }).waitFor();
  assert.equal(await second.getByTestId('counter-value').innerText(), '—');
  await h.screenshot(second, 'read-error');
  h.pass('Real database outage gives visible read/write errors with no fake success');
  await h.dc(['up', '-d', '--wait', '--wait-timeout', '120', 'db']);
  await page.getByRole('button', { name: '重新读取', exact: true }).click(); await h.visible(page, -1);
  await h.stored(-1, 'recovered');
  await h.click(page, 'increment', 0);
  await h.stored(0, 'continued');
  await page.setViewportSize({ width: 390, height: 844 });
  await h.screenshot(page, 'mobile');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(h.meta.pageErrors ?? [], []);
  h.pass('Recovery re-reads original data and allows a new write; mobile layout fits');
  success = true;
} finally { await h.close(success); }
console.log(`PASS Counter UI. Evidence: ${h.artifacts}`);
